DROP TABLE CLASE_MIEMBRO;
DROP TABLE CLASE;
DROP TABLE MIEMBRO;
DROP TABLE MONITOR;
DROP TABLE USUARIO;
DROP TABLE ROL;

DROP SEQUENCE SEQ_CLASE;
DROP SEQUENCE SEQ_MIEMBRO;
DROP SEQUENCE SEQ_MONITOR;
DROP SEQUENCE SEQ_ROL;