CREATE TABLE ROL (
    ID_ROL NUMBER,
    DESCRIPCION VARCHAR2(100),
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIO (
    ID_USUARIO VARCHAR2(100),
    NOMBRE VARCHAR2(100),
    APELLIDOS VARCHAR2(100),
    DNI VARCHAR2(20),
    EMAIL VARCHAR2(100),
    PASSWD VARCHAR2(100),
    ID_ROL NUMBER,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);

CREATE TABLE MONITOR (
    ID_MONITOR NUMBER,
    ID_USUARIO VARCHAR2(100),
    CONSTRAINT PK_MONITOR PRIMARY KEY (ID_MONITOR),
    CONSTRAINT FK_MONITOR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE MIEMBRO (
    ID_MIEMBRO NUMBER,
    ID_USUARIO VARCHAR2(100),
    CONSTRAINT PK_MIEMBRO PRIMARY KEY (ID_MIEMBRO),
    CONSTRAINT FK_MIEMBRO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE CLASE (
    ID_CLASE NUMBER,
    ID_MONITOR NUMBER,
    NOMBRE VARCHAR2(100),
    DESCRIPCION VARCHAR2(255),
    SALA VARCHAR2(100),
    DIA VARCHAR2(20),
    HORA DATE,
    DURACION NUMBER,
    LIMITE_MIEMBROS NUMBER,
    CONSTRAINT PK_CLASE PRIMARY KEY (ID_CLASE),
    CONSTRAINT FK_CLASE_MONITOR FOREIGN KEY (ID_MONITOR) REFERENCES MONITOR(ID_MONITOR)
);

CREATE TABLE CLASE_MIEMBRO (
    ID_CLASE NUMBER,
    ID_MIEMBRO NUMBER,
    CONSTRAINT PK_CLASE_MIEMBRO PRIMARY KEY (ID_CLASE, ID_MIEMBRO),
    CONSTRAINT FK_CLASE FOREIGN KEY (ID_CLASE) REFERENCES CLASE(ID_CLASE),
    CONSTRAINT FK_MIEMBRO FOREIGN KEY (ID_MIEMBRO) REFERENCES MIEMBRO(ID_MIEMBRO)
);

CREATE SEQUENCE SEQ_ROL
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE SEQ_MONITOR
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE SEQ_MIEMBRO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE SEQ_CLASE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
